[package]
name = "hello"
version = "0.1.0"
<<<<<<< HEAD
authors = ["James <r.j.shimizu@jaist.ac.jp>"]
=======
>>>>>>> 97b2c1c (Restart commit as study, Listening for incoming streams and printing a message when we receive a stream)
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
